version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cambridge-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount the interface directory to watch for changes
      - ./interface:/app/interface:ro
      # Mount the backend code for development
      - ./backend:/app
      # Exclude generated files from mounting to avoid conflicts
      - /app/generated
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Future frontend service (commented out for now)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: cambridge-frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

networks:
  default:
    name: cambridge-network 